name: Build and Deploy to gh-pages

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version (or the latest stable)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project using Webpack
      - name: Build project
        run: npm run build

      # Step 5: Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
